name: Generate Meme Keywords

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的 git 历史

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Backup current meme_keywords.md if exists
        run: |
          if [ -f docs/meme_keywords.md ]; then
            cp docs/meme_keywords.md docs/meme_keywords.md.backup
            echo "Backed up existing meme_keywords.md"
          else
            echo "No existing meme_keywords.md found"
          fi

      - name: Run meme_keywords.py
        run: python meme_keywords.py

      - name: Check if meme_keywords.md changed
        id: check_diff
        run: |
          if [ ! -f docs/meme_keywords.md.backup ]; then
            echo "No backup file, this is a new file."
            echo "changed=true" >> $GITHUB_OUTPUT
          elif cmp -s docs/meme_keywords.md docs/meme_keywords.md.backup; then
            echo "No changes detected."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Update GitHub Wiki
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 克隆 Wiki 仓库
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jinjiao007/meme-generator-jj.wiki.git wiki
          cd wiki
          
          # 复制生成的文档到 Wiki，重命名为表情列表.md
          cp ../docs/meme_keywords.md "表情列表.md"
          
          # 检查是否有变化
          if git diff --quiet; then
            echo "No changes in wiki"
          else
            git add "表情列表.md"
            git commit -m "🤖 Auto-update 表情列表"
            git push origin master
            echo "Wiki updated successfully"
          fi

      - name: Cleanup backup file
        if: always()
        run: |
          if [ -f docs/meme_keywords.md.backup ]; then
            rm docs/meme_keywords.md.backup
            echo "Cleaned up backup file"
          fi
