name: Generate Meme Keywords

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的 git 历史

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Backup current meme_keywords.md if exists
        run: |
          if [ -f docs/meme_keywords.md ]; then
            cp docs/meme_keywords.md docs/meme_keywords.md.backup
            echo "Backed up existing meme_keywords.md"
          else
            echo "No existing meme_keywords.md found"
          fi

      - name: Run meme_keywords.py
        run: python meme_keywords.py

      - name: Check if meme_keywords.md changed
        id: check_diff
        run: |
          if [ ! -f docs/meme_keywords.md.backup ]; then
            echo "No backup file, this is a new file."
            echo "changed=true" >> $GITHUB_OUTPUT
          elif cmp -s docs/meme_keywords.md docs/meme_keywords.md.backup; then
            echo "No changes detected."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Switch to docs branch and commit changes
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 保存生成的文档到临时位置
          cp docs/meme_keywords.md /tmp/meme_keywords.md
          
          # 清理工作目录，避免切换分支时冲突
          rm -rf docs/
          
          # 检查 docs 分支是否存在
          if git ls-remote --heads origin docs | grep -q refs/heads/docs; then
            echo "docs branch exists, checking out"
            git fetch origin docs
            git checkout -B docs origin/docs
          else
            echo "docs branch does not exist, creating orphan branch"
            git checkout --orphan docs
            # 删除所有文件
            git rm -rf .
            # 创建 docs 目录
            mkdir -p docs
          fi
          
          # 复制生成的文档
          cp /tmp/meme_keywords.md docs/meme_keywords.md
          git add docs/meme_keywords.md
          git commit -m "🤖 Auto-generate meme_keywords.md"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jinjiao007/meme-generator-jj.git
          git push origin docs

      - name: Cleanup backup file
        if: always()
        run: |
          if [ -f docs/meme_keywords.md.backup ]; then
            rm docs/meme_keywords.md.backup
            echo "Cleaned up backup file"
          fi
